### Listar produtos
GET http://localhost:4200/List HTTP/1.1

### Cadastrar produto
POST http://localhost:4200/Create HTTP/1.1
Content-Type: application/json

{
    "Descricao": "Bolacha",
    "DataCriacao": "10-17-2021 15:40:10"
}

###
PUT http://localhost:4200/Update HTTP/1.1
{
    "Codigo" : 1,
    "Descricao": "Arroz"
}

###
GET http://localhost:4200/GetOne HTTP/1.1
{
    "codigo" : 1
}