### Listar produtos
GET http://localhost:4200/List HTTP/1.1

### Cadastrar produto
POST http://localhost:4200/Create HTTP/1.1
Content-Type: application/json

{
    "Descricao": "Pao de alho",
    "DataCriacao": "10-17-2021 15:40:10"
}

### Update
POST http://localhost:4200/Update HTTP/1.1
Content-Type: application/json

{
    "Codigo": 3,
    "Descricao": "Mainzena",
    "DataAtualizacao": "01-17-2022 16:58:00"
}

### GetOne
POST http://localhost:4200/GetOne HTTP/1.1
Content-Type: application/json

{
    "Codigo": 3
}

### Delete
DELETE http://localhost:4200/DELETE HTTP/1.1
Content-Type: application/json

{
    "Codigo": 3
}
